name: carfoin
description: Gestor de Carteras de Fondos de Inversión
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.2.2+25

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  csv: ^6.0.0
  file_picker: ^8.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  flutter_markdown: ^0.7.3
  go_router: ^14.2.2
  cupertino_icons: ^1.0.6
  http: ^1.1.2
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0  
  fl_chart: ^0.68.0
  url_launcher: ^6.2.2
  share_plus: ^10.0.0
  html: ^0.15.4
  yahoo_finance_data_reader: ^1.0.8
  printing: ^5.11.1
  sentry: ^8.6.0  
  sqflite_common_ffi: ^2.3.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  ios: false

flutter:
  uses-material-design: true

  assets:
    - assets/


