name: carfoin
description: Gestor de Carteras de Fondos de Inversión
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.2.1+24

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  csv: ^5.1.1
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 
  flutter_markdown: ^0.6.18+2
  go_router: ^13.0.0
  cupertino_icons: ^1.0.6
  http: ^1.1.2
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0  
  fl_chart: ^0.66.0
  url_launcher: ^6.2.2
  permission_handler: ^11.1.0
  share_plus: ^7.2.1
  html: ^0.15.4
  yahoo_finance_data_reader: ^1.0.8
  printing: ^5.11.1
  sentry: ^7.14.0  
  sqflite_common_ffi: ^2.3.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  ios: false

flutter:
  uses-material-design: true

  assets:
    - assets/


